# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[global.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"

[debug]
address = "127.0.0.1"
port = 9000
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "0.0.0.0"
port = 9000
log_level = "critical"
# don't use this key! generate your own and keep it private!
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
